import Head from 'next/head'
import {useEffect, useState} from "react";
import calculatePasswordStrength from "@/utils/crackTime";
import {ZxcvbnResult} from "@zxcvbn-ts/core";
import "../utils/crackTime"

const HomePage = () => {

    const [searchTerm, setSearchTerm] = useState('');
    const [result, setResult] = useState<ZxcvbnResult|null>(null)

    useEffect(() => {
        if(searchTerm?.length > 0) {
            calculatePasswordStrength(searchTerm).then((r) => setResult(r));

        }
    }, [searchTerm]);
    console.log(result)
   
  return (
    <>
      <Head >
        <title>Password Strength Checker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div  >
          <h1 className='text-center text-3xl'>Password Strength Checker</h1>
        </div>
        <div className='text-center text-xl'>
          <h1>Enter password</h1>
         <input
            type="password"
            className="outline-red-600"
            placeholder="Enter Your Password"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
         />
          {result && (
          <div >
              <div >
                  {result.score/5 * 100}% ({result.score}/5)
              </div>
              <div>
                
              {result?.calcTime} <br />
              {result?.feedback?.warning} <br />
              {result?.feedback?.suggestions}<br/>
              </div>
              
          </div>)}
          <div>
          
          </div>
          </div>
      </main>
    </>
  )
};

export default HomePage;
